### ISSUE TITLE
Reactin NavLinkit tehtävälistauksessa

### ISSUE THREAD

**Issue by Jaakkonen** [rage/ohjelmointi-19#10]
Feature request:

Tehtävälistaukseen osien etusivuilla (https://ohjelmointi-19.mooc.fi/osa-123) voisi laittaa listaan navlinkit, joista pääsee suoraan kyseiseen tehtävään.
Tehtävien identifiointi (css identifioija johon sivun voi avata) voidaan tehdä h-123 listan avaimen perusteella (loihtii divin jolla on esimerkiksi tämä avain classNamena ja tekee navigoinnin siihen)

**Comment by nygrenh** [comment]
Joo, toi on tulossa kuhan vaan ehditään.

**Comment by ljleppan** [comment]
Lisäehdotuksena, tehtävien numerointi "Lista osan tehtävistä" -listauksessa voisi olla  synkroonissa TMC:ssä olevien tehtävien numeroinnin kanssa. Nyt esim. mäppäys ilmauksesta "viikon kaksi 22. tehtävä" tehtävänantoon on hieman raskas.

**Comment by nygrenh** [comment]
@ljleppan Toi on vähäsen ongelmallinen kun kaikki kurssin tehtävät ei ole TMC:ssä, ja tämän takia TMC-tehtävien numerot eivät oikastaan voi matchata noihin kurssimateriaalin numeroihin ilman että kaikki TMC-tehtävät nimettäisiin uudelleen. Ja TMC-tehtävien uudelleennimentä tässä vaiheessa kurssia ei oikeastaan onnistu.

**Comment by nygrenh** [comment]
Ominaisuus toteutettu, kiitos ehdotuksesta!
