### ISSUE TITLE
Tehtävät eivät lataudu

### ISSUE THREAD

**Issue by HessuHiiri** [rage/ohjelmointi-19#100]
Kun lataan Netbeans with TMC ohjelmointiympäristön, kurrsin tehtävät eivät lataudu tietokoneelleni, en saa edes vaihtoehtoa ladata tehtäviä. Olen yrittänyt Netbeansin latausta sekä windowsilla että linuxilla mutta tehtäviä ei lataudu. Voiko tehtävät ladata jostain muualta?
Edit: Kun vaihdan kurssin aikatauluttomaksi tehtävät latautuvat mutta en pysty lähettämään niitä palvelimelle kun vaihdan takaisin aikataululliselle kurssille.

**Comment by reettap** [comment]
Hei!
Aikataulullisen kurssin suoritus on mahdollista ainoastaan kurssin aikataulun mukaisesti, mikäli deadline on jo ohi, tehtäviä ei saa ladattua. Siinä tapauksessa on suositeltavaa aloittaa aikatauluton kurssi.
