### ISSUE TITLE
macOS vaatii lisäoikeuksia osan 12 testien toimimiseen

### ISSUE THREAD

**Issue by marko2383** [rage/ohjelmointi-19#101]
Osassa 12 aloitetaan käyttämään graafista JavaFX-kirjastoa, ja ainakin tehtävässä 6 testit vaativat esim. hiiren automaattista ohjaamista. macOS:n tietoturvaominaisuudet estävät tällaisen käyttäytymisen oletuksena.

Kun testiohjelma yrittää siirtää hiirtä, käyttöjärjestelmä ponnauttaa ikkunan, joka vie käyttäjän asetuksiin. Tämä ikkuna kuitenkin näkyy alle sekunnin ajan, sillä testiohjelma varmaankin tulkitsee hiiren liikkumattomuuden tarkoittavan, että testi epäonnistui, ja sulkee sovelluksen ja samalla em. ponnahdusikkunan. tmcbeans-sovellus pitää siis itse manuaalisesti lisätä sallituksi sovellukseksi järjestelmäasetuksista (System Preferences –> Security & Privacy –> Privacy –> Accessibility –> "Click the lock to make changes." –> plus-kuvake –> tmcbeans.app –> Open).

Mikäli edellä mainittuja muutoksia ei tee käyttöjärjestelmän turvallisuusasetuksiin, joidenkin testien läpäiseminen macOS:llä on mahdotonta. Olisi hyödyllistä, mikäli osan 12 alussa olisi jonkinlainen ohjeistus näiden asetuksien tekemisestä.

**Comment by Redande** [comment]
Hei, kiitos kun toit tämän ilmi!

Materiaaleihin on nyt lisätty ohjeet oikeuksien lisäämisestä macOS:lla.
