### ISSUE TITLE
Tehtävä 13_3 tehtävänanto hämäävä k

### ISSUE THREAD

**Issue by AriMartti** [rage/ohjelmointi-19#105]
> Laske korko vuosittain vuoden lopussa olevan tallennuksen perusteella (eli hieman optimistisesti). Esimerkiksi kun kuukausittainen tallennus on 50 ja korko 5%, tulee kuukausikohtaisten korkojen olla [(0, 0), (1, 52.5), (2, 107.625), (3, 165.50625), ...] — huomaa, että kaavioon tulee kuitenkin vuosittaiset tilanteet.

Yllä on laskettu kuten kuukausikohtainen korko olisi 5%, mitä se ei ikinä missään tilanteessa tulisi olemaan. Testit eivät menneet läpi, vaikka laskinkin kuukausikorot täsmälleen tuolla tavalla. Kun en lisännyt korkoa säästösaldoon kuukausittain, testitkin menivät läpi.

**Comment by reettap** [comment]
Kiitos!
Esimerkki on nyt muutettu muotoon:
"Laske korko vuosittain vuoden lopussa olevan tallennuksen perusteella (eli hieman optimistisesti). Esimerkiksi kun kuukausittainen tallennus on 50 ja vuosikorko 5%, tulee vuosittaisten summien korkoineen olla [(0, 0), (1, 630), (2, 1291.5), (3, 1986.075), ...]"
