### ISSUE TITLE
Osa07_02.NestesailiotOlioilla

### ISSUE THREAD

**Issue by riuska** [rage/ohjelmointi-19#107]
Tehtävän 07.02 automaattitesti ilmoittaa virheen:

> FAIL: NestesailiotOlioillaTest lisaa1
> Kun syöte on:
> lisaa 1
> lopeta
> 
> Tulostuksessa pitäisi olla rivi:
> Ensimmäinen: 0/100
> Nyt tulostus oli:
> Ensimmäinen: 1/100
> Ensimmäinen: 1/100
> Toinen: 0/100

Mielestäni testin tulos on virheellinen. Eikös yhden yksikön lisääminen ekaan säiliöön pitäisi olla hyväksyttävää, eli tuloksena pitäisikin olla 1/100 eikä 0/100, kun lisäys tehdään heti aluksi?

**Comment by reettap** [comment]
Hei!
Testi näyttäisi toimivan juurin niinkuin pitääkin. Tulostuksessa kuuluisi ensin olla "Ensimmäinen: 0/100", koska säiliö on ennen lisäystä tyhjä.
