### ISSUE TITLE
Osa 3 -3 Indekseistä ja muistin rakenteesta int-tyypin suurin arvo

### ISSUE THREAD

**Issue by Saryos** [rage/ohjelmointi-19#109]
"Javassa int-tyyppinen muuttuja on 32-bitin kokoinen ja se voi esittää korkeintaan 2^32-1 kokoista lukua."  
Suurin esitettävä lukuarvohan on 2^31-1.

**Comment by reettap** [comment]
Korjattu, kiitos!
