### ISSUE TITLE
Osa 7 Tiedon järjestäminen /Pienimmän arvon indeksi esimerkki metodin käytöstä, virheellinen new

### ISSUE THREAD

**Issue by Saryos** [rage/ohjelmointi-19#110]
Kutsuesimerkki sisältää ylimääräisen new-komennon:

Seuraava koodi esittelee metodin toimintaa:

// indeksit:   0  1  2  3  4
int[] luvut = {6, 5, 8, 7, 11};
System.out.println("Pienimmän indeksi: " + new Paaohjelma.pienimmanIndeksi(luvut));

**Comment by reettap** [comment]
Korjattu, kiitos! :)
