### ISSUE TITLE
Osa 8 - Abstraktit luokat: pieni typo

### ISSUE THREAD

**Issue by jtompuri** [rage/ohjelmointi-19#112]
Tehdään toistuu kahdesti virkkeessä:

"Abstrakti luokka yhdistää rajapintoja ja perintää. Niistä ei voi tehdä ilmentymiä, vaan ilmentymät tehdään tehdään abstraktin luokan aliluokista."

**Comment by reettap** [comment]
Korjattu, kiitos!
