### ISSUE TITLE
Osa 11: Moniuloitteinen tieto -esimerkissä väärä muuttuja

### ISSUE THREAD

**Issue by jtompuri** [rage/ohjelmointi-19#114]
Esimerkin sisemmässä for-silmukassa on muuttuja `y`, kun pitäisi olla muuttuja `rivi` tai arvo '0':

`for (int sarake = 0; sarake < kaksiulotteinenTaulukko[y].length; sarake++) {`
=>
` for (int sarake = 0; sarake < kaksiulotteinenTaulukko[rivi].length; sarake++) {`

Sama virhe toistuu kahdessa esimerkissä.

**Comment by reettap** [comment]
Korjattu, kiitos!
