### ISSUE TITLE
Osa 11: Moniuloitteinen tieto / typo

### ISSUE THREAD

**Issue by jtompuri** [rage/ohjelmointi-19#115]
Voimme muuttaa taulukon arvoja kuten ennenkin. Alla asetamme **kahteen** kohtaan uudet arvot.

=> 

Voimme muuttaa taulukon arvoja kuten ennenkin. Alla asetamme **kolmeen** kohtaan uudet arvot.

**Comment by reettap** [comment]
Korjattu!
Kiitos :)
