### ISSUE TITLE
Pieni typo tehtäväkolikkojen selityksessä

### ISSUE THREAD

**Issue by ljleppan** [rage/ohjelmointi-19#12]
Tehtävänantojen lopussa olevassa kolikoista kertovassa tekstissä on typo. Sen ensimmäinen lause alkaa nyt

> Joka kerta kun olet saanut 16:ta tehtävää tehtyä, saat kolikon.

Ongelma on siis ilmauksessa "_16:ta_", joka on auki kirjoitettuna "_kuuttatoista_", tässä kontekstissa siis "_Joka kerta kun olet saanut kuuttatoista tehtävää tehtyä, saat kolikon._". Pitäisi siis olla ihan vain "16" ilman auki kirjoitettua sijapäätettä.

Kts. http://www.kielitoimistonohjepankki.fi/haku/numerot/ohje/269

**Comment by nygrenh** [comment]
Kiitos!
