### ISSUE TITLE
Typo tehtävänanto-templatessa

### ISSUE THREAD

**Issue by crunsk** [rage/ohjelmointi-19#13]
Kolikoiden selostuksen jälkeen tulee lause "**Pysyt** katsomaan mallivastauksen ilman kolikkoja Test My Code -palvelusta sen jälkeen kun olet saanut tehtävän oikein.".
Lauseen pitäisi varmaan alkaa sanalla "pystyt"?

**Comment by Redande** [comment]
Hei, kiitos typon ilmoittamisesta!

Tämä on nyt korjattu commitissa 77efbd2d7fc3d15fa6560314b3c3187e8104072b
