### ISSUE TITLE
Typo osassa 3, 1-ohjelmien-ymmarrettavyydesta.md

### ISSUE THREAD

**Issue by crunsk** [rage/ohjelmointi-19#17]
Rivillä 188: Tarkasteltava ohjelma sisältää **hakualgoritmi** nimeltä "puolitushaku".
=> Tarkasteltava ohjelma sisältää hakualgoritmin nimeltä "puolitushaku".
[Linkki kohtaan](https://github.com/rage/ohjelmointi-19/blame/master/data/osa-3/1-ohjelmien-ymmarrettavyydesta.md#L188)

**Comment by avihavai** [comment]
Kiitos! Tämä on nyt korjattu :+1:
