### ISSUE TITLE
Mahdollinen typo - ohjelmointi-19/data/osa-3/1-ohjelmien-ymmarrettavyydesta.md       

### ISSUE THREAD

**Issue by Nurou** [rage/ohjelmointi-19#18]
Osan viimeinen rivi:
'Jos idea on hyvä, sitä jatkokehitetään -- samalla myös ohjelma ja kehittyy.'
Olisiko se 'ohjelma kehittyy'?

**Comment by avihavai** [comment]
Ihan oikea typo se oli, kiitos! :+1:
