### ISSUE TITLE
Osa 3 / taulukot: puolipiste puuttuu esimerkistä "Taulukko metodin parametrina"

### ISSUE THREAD

**Issue by jtompuri** [rage/ohjelmointi-19#20]
"Taulukko metodin parametrina" esimerkkikoodin seuraavalta riviltä puuttuu puolipiste:
`int luku = kokonaislukuTaulukko[indeksi]`

Lähdekoodissa rivi 339.

**Comment by avihavai** [comment]
Äh, kiitos :1st_place_medal:
