### ISSUE TITLE
Tehtävä Osa01_39NegatiivistenLukujenMaara antaa virheen

### ISSUE THREAD

**Issue by LMFARMI** [rage/ohjelmointi-19#25]
### Tehtävä Osa01_39NegatiivistenLukujenMaara ei hyväksy vastausta
Tehtävä Osa01_39.NegatiivistenLukujenMaara ei kelpuuta edes mallivastausta vaan testi epäonnistuu. Ongelmaksi kuvataan, että ohjelman pitäisi tulostaa vain negatiivisten lukujen lukumäärä vaikka ohjelma toistaa myös pyynnön Syötä luku. Tämä antaa virheen ja tehtävää ei voi tallettaa serverille.
Miten pitäisi toimia, että tehtävän saa suoritetuksi ?

**Comment by reettap** [comment]
Tällaisessa auttaa yleensä clean&build eli Netbeansin ylävalikossa näkyvä nappi jossa on harjan ja vasaran kuva.
