### ISSUE TITLE
Osa 2 tehtävä 6 MerkkijonojenLukumaara - virheilmoitus

### ISSUE THREAD

**Issue by vviii** [rage/ohjelmointi-19#29]
En ymmärrä, mikä tässä on vialla. Saan virheilmoituksen: 

> "Jotain kummallista tapahtui. Saattaa olla että class MerkkijonojenLukumaara-luokan public static void main(String[] args) -metodi on hävinnyt
> tai ohjelmasi kaatui poikkeukseen. Lisätietoja java.util.NoSuchElementException: No line found"

Koko koodi: 
`
import java.util.Scanner;

public class MerkkijonojenLukumaara {

    public static void main(String[] args) {
        Scanner lukija = new Scanner(System.in);

        int summa = 0;
                
        while (true) {
            String luettu = lukija.nextLine();
            
            if (luettu.equals("lopeta")) {
                break;
            }
            summa = summa + 1;
        }
        System.out.println(summa); 
    }  
}
`

**Comment by arttuoll** [comment]
Sama ongelma

**Comment by reettap** [comment]
Tämä on sama ongelma kuin #3 . 
Apua ongelmiin saa kurssin tukiväyliltä: https://ohjelmointi-19.mooc.fi/tukivaylat
