### ISSUE TITLE
Osa 3 Tehtävä 33 Joka toinen sana, virheellinen sanamuoto?

### ISSUE THREAD

**Issue by ShootingStar91** [rage/ohjelmointi-19#30]
Osan 3 Tehtävässä 33 Joka toinen sana pyydetään luettelemaan joka toinen syötetty sana **ensimmäisestä indeksistä** lähtien. Tehtävä kuitenkin menee läpi vain jos aloitetaan indeksistä 1, joka on tietenkin _toinen indeksi_ sillä ensimmäinen indeksi on 0. Tai näin ainakin itse oletin, ja se tuntuu luontevimmalta. Vai mikäs indeksi 0 sitten olisi järjestysnumeroilla ilmaistuna, _nollas_ indeksi?

**Comment by avihavai** [comment]
Kiitos palautteesta! Tuossa juurikin pakotettiin myös kertaamaan tuota nollatta indeksiä. Lisäsin tehtävänantoon maininnan (ei nollannesta). :+1:
