### ISSUE TITLE
Osa 2, Tehtävä 33, 3 rivin kokoisen kolmion testi case väärä?

### ISSUE THREAD

**Issue by markulai** [rage/ohjelmointi-19#31]
Rivillä 82 testi vaikuttaa hämärältä... Ei kai tuollaista kolmiota pitäisi tulostaa?
assertEquals("Tulostit väärin kun kutsuttiin tulostaKolmio(3).", "  *\n **\n***\n", out);

Olisiko oikeampi ao.? 
assertEquals("Tulostit väärin kun kutsuttiin tulostaKolmio(3).", "  *\n ***\n*****\n", out);

**Comment by AriMartti** [comment]
>         assertEquals("Tulostit väärin kun kutsuttiin tulostaKolmio(3).", "  *\n **\n***\n", out);

Minun lataamassani testipaketissa tuo näyttää täsmälleen oikealta.

**Comment by markulai** [comment]
Moi eikös tuon tulostaKolmio(3):n pitäisi tulostaa ennemminkin symmetrinen kolmio:
  *
 ***
*****

Tuostahan tulee vain?
  *
 **
***

**Comment by markulai** [comment]
Minkäs pirun takia tuosta kommentista näyttäisi jäävän osa pois...
siis minun kolmion funktio tulostaa:
'   *
' ***
'***** 

ja näköjään tuossa odotetaan
'  *
' **
'***

**Comment by AriMartti** [comment]
Lukaisepa ohjeet, miltä oikealle nojaavan kolmion kuuluu näyttää: https://ohjelmointi-19.mooc.fi/osa-2/3-metodit#programming-exercise-tulostelua-like-a-boss-3-osaa

**Comment by Redande** [comment]
Hei,

Voit kysyä apua tehtävissä kurssin tukiväyliltä: https://ohjelmointi-19.mooc.fi/tukivaylat
Esimerkiksi Moodle-foorumille voi lähettää tämän tyyppisiä kysymyksiä.
