### ISSUE TITLE
osa02-Osa02_09.YkkostenOsuus testien tulokset failaavat hämmentävästi

### ISSUE THREAD

**Issue by AriMartti** [rage/ohjelmointi-19#35]
![image](https://user-images.githubusercontent.com/876555/51737002-2f295f80-2094-11e9-8123-288e2f2c9d62.png)

Testin tulostus on hämäävä, sillä opiskelijan koodi tulosti, mutta vääriä asioita (hän lisäsi lukulaskuria myös syötteen ollessa "0", joka sai aikaan väärän keskiarvon).

**Comment by reettap** [comment]
Korjattu, kiitos! :)
