### ISSUE TITLE
osa02_10, positiivisten lukujen keskiarvo, en saa toimimaan

### ISSUE THREAD

**Issue by SanniAh** [rage/ohjelmointi-19#38]
Käytin kolikonkin, että saisin selvää, mikä mättää, muutin koodin täysin vastaamaan mallivastausta, eikä tuotos silti toimi oikein. 
Missä vika?

**Comment by Redande** [comment]
Hei,

Voit kysyä apua tehtävissä kurssin tukiväyliltä: https://ohjelmointi-19.mooc.fi/tukivaylat
Esimerkiksi Moodle-foorumille voi lähettää tämän tyyppisiä kysymyksiä.
