### ISSUE TITLE
Esimerkkitulosteet näkyvät väärin

### ISSUE THREAD

**Issue by ljleppan** [rage/ohjelmointi-19#4]
Tavattu Firefoxilla (Win10) ja Safarilla.

`<programming-exercise>` lohkon sisällä olevat `<sample-output>` lohkot näkyvät väärin ainakin ym. selaimilla.

![Esimerkki](http://perfectlylegit.website/esimerkki.png)

**Comment by nygrenh** [comment]
Tulee siis vain silloin kun sivulle ei olla tultu sivun sisäisellä
siirtymällä. Gatsby on vähän ilkeä noissa.

**Comment by nygrenh** [comment]
Pitäisi olla nyt korjattu. Kiitos!
