### ISSUE TITLE
Osa02_04.TietoaLuvuista, palautusongelma.

### ISSUE THREAD

**Issue by RipaJ** [rage/ohjelmointi-19#43]
Tietoa luvuista tehtävä toimii omalla koneellani virheettömästi. Lähetettäessä tehtävän saan vataukseksi että yhtäsuurien numeroiden tulostus ei toimi. En koodannut ohjelmaa toiseen muotoon, vielä. Olisiko jokin bugi? Muualla kuin minun päässä? Win 10, kaikki softallisesti päivitetty mitä löytyy.
Alla virheilmo:

Kun syöte oli 5 
5 
, odotettiin tulostusta: yhtä suuri Tulostusta ei löytynyt

Minun koodi:

        //Luetaan kaksi lukua ja vertaillaan niitä
        int ekaLuku = Integer.valueOf(lukija.nextLine());
        int tokaLuku = Integer.valueOf(lukija.nextLine());
        
        if (ekaLuku < tokaLuku){    //Onko ekaLuku pienempi kuin tokaLuku
            System.out.println("luku " + ekaLuku  + " on pienempi kuin " + tokaLuku + ".");
        }else if(ekaLuku > tokaLuku){   //Onko ekaLuku suurempi kuin tokaLuku
            System.out.println("luku " + ekaLuku  + " on suurempi kuin " + tokaLuku + ".");
        }else{  //Muutoin niiden on oltava yhtäsuuret
            System.out.println("luku " + ekaLuku  + " on yhtäsuuri kuin " + tokaLuku + ".");
        }

**Comment by Redande** [comment]
Viimeisessä else-lohkossa rivillä `System.out.println("luku " + ekaLuku  + " on yhtäsuuri kuin " + tokaLuku + ".");` on kirjoitusvirhe; "yhtä suuri" pitää olla kirjoitettuna erikseen.  Testit ovat pikkutarkkoja tällaisista, sen takia testit eivät mene läpi.

Tehtäviin liittyviin kysymyksiin vastataan ensisijaisesti tukikanavillamme, esimerkiksi Moodle-foorumilla. Tukikanavat löytyvät täältä: https://ohjelmointi-19.mooc.fi/tukivaylat

**Comment by RipaJ** [comment]
No niinpäs onkin. En vielä osannut Netbeansissä painaa nappia, run tests locally. Se olisi heti selventänyt tilanteen. Ehkäpä ohjeistuksen osalta voisi mennä hieman syvemmälle aloituksessa jo.

Kiitos.
