### ISSUE TITLE
Typo osassa 5 Alkeistyyppiset muuttujat

### ISSUE THREAD

**Issue by crunsk** [rage/ohjelmointi-19#46]
Potenssiluvut eivät jostain syystä näy oikein kappaleessa https://ohjelmointi-19.mooc.fi/osa-5/2-alkeis-ja-viittaustyyppiset-muuttujat.
Ainakin firefoxilla näkyyvät minulla näin:
`int (keskikokoista kokonaislukua kuvaava 32 bittiä sisältävä arvo, välillä -2<sup>31</sup> ja 2<sup>31</sup>-1), long (isohkoa kokonaislukua kuvaava 64 bittiä sisältävä arvo, välillä -2<sup>63</sup> ja 2<sup>63</sup>-1)`

**Comment by Redande** [comment]
Hei, kiitos kun toit tämän ilmi! Nyt noiden pitäisi olla korjattu.
