### ISSUE TITLE
Mistä saan ladattua tokan osan tiedostot?

### ISSUE THREAD

**Issue by Steellow** [rage/ohjelmointi-19#47]
Ekassa osassa joka tehtävälle oli oma projekti filu netbeanssissa, en löydä niitä mistään kakkos osaan

**Comment by nygrenh** [comment]
NetBeans -liitännäinen tarjoaa sinulle seuraavan osan tehtäviä, kun olet saanut tarpeeksi edellisen osan ohjelmointitehtävien pisteistä. Aikataulullisella kurssilla tämä raja on 25% ja aikatauluttomalla kurssilla tämä raja on 90%.

Tälläisiin ongelmiin saa paremmin vastauksia meidän tukikanavilta, esim Moodle-foorumilta: https://ohjelmointi-19.mooc.fi/tukivaylat
