### ISSUE TITLE
Malliratkaisussa 02_22 virhe

### ISSUE THREAD

**Issue by JessicaJones111** [rage/ohjelmointi-19#48]
Tehtävän 02_22 malliratkaisussa on sellainen virhe, että se ei pyydä käyttäjää syöttämään lukua. Ohjelmassa on otettu lukija scanner käyttöön, mutta käyttäjältä ei pyydetä lukua. Siten malliratkaisulla ohjelma "toimii", mutta ei pyydä käyttäjältä mitään eikä siten tulosta mitään.

**Comment by Redande** [comment]
Hei, tuossa tehtävässä ei oikeastaan ole tarkoitus kysyä syötettä käyttäjältä ollenkaan. Tehtävässä on tarkoituksena luoda metodi tulostaLukuunAsti(). Lukija löytyy tehtäväpohjasta vain oman koodin testaamista varten.
