### ISSUE TITLE
Osa01_42.LukujenKeskiarvo.java - ohjelma toimii, mutta palautuksessa virhe

### ISSUE THREAD

**Issue by keravalainen** [rage/ohjelmointi-19#50]
Palauttaessa vastausta tulee seuraava virheilmoitus:
FAIL: LukujenKeskiarvoTest test1
Kun syötettiin:
-5
4
-3
1
0

Ohjelmassa pitäisi olla tulostus "Lukujen keskiarvo -0.75".
Nyt tulostus oliSyötä luku
Syötä luku
Syötä luku
Syötä luku
Syötä luku
Keskiarvo on -0.75

Tämä sama ongelma minulla esiintyi jo edellisessä tehtävässä, mutta sain sen läpi mallivastauksen avulla. Ohjelma toimii juuri niin kuin pitää ja muutenkin oikein tehty. Miksi ihmeessä tämä virheilmoitus?

**Comment by nygrenh** [comment]
Hei,

Voit kysyä apua tehtävissä kurssin tukiväyliltä: https://ohjelmointi-19.mooc.fi/tukivaylat
Esimerkiksi Moodle-foorumille voi lähettää tämän tyyppisiä kysymyksiä.
