### ISSUE TITLE
Osa 5, Katsaus olio-ohjelmointiin: virhe Kello-esimerkissä

### ISSUE THREAD

**Issue by jtompuri** [rage/ohjelmointi-19#51]
Kello-esimerkin koodissa Kello-luokan nimen perässä on virheellisesti sulut: 

public class Kello() {
    private Viisari tunnit;
    private Viisari minuutit;
    private Viisari sekunnit;
    ...

**Comment by reettap** [comment]
Korjattu, kiitos! :)
