### ISSUE TITLE
Osa 5.2: Esimerkin Henkilo-luokasta  puuttuu metodi nuorenna()

### ISSUE THREAD

**Issue by jtompuri** [rage/ohjelmointi-19#53]
Osassa 5.2 Alkeis- tai viittaustyyppinen muuttuja metodin parametrina:
Esimerkin Henkilo-luokalta puutuu metodi nuorenna(), vaikka sitä käytetään esimerkissä.

**Comment by reettap** [comment]
Hei!
Nuorenna-metodi löytyy pääohjelman alareunasta staattisena metodina.
