### ISSUE TITLE
Osa6_04.Lyhenteet testin lyhenteenLisaysHakuJaPoisto koodiehdotuksessa virhe?

### ISSUE THREAD

**Issue by crunsk** [rage/ohjelmointi-19#56]
Jos testi epäonnistuu, tulostetaan koodin pätkä, jolla voi testata virhettä.
Ehdotetussa koodissa taitaa olla kirjoitusvirhe kohdassa: lyhenteet.v(\"lol\")

**Comment by reettap** [comment]
Kiitos! Testi on korjattu. :)
