### ISSUE TITLE
Osa 6_07.Velkakirja

### ISSUE THREAD

**Issue by pjehkonen** [rage/ohjelmointi-19#57]
Kurssimateriaali sanoo (Osa 6 tehtävä 07 Velkakirja):

"
metodi public void asetaLaina(String kenelle, double maara) tallettaa velkakirjaan merkinnän lainasta tietylle henkilölle.
"
Kun taas tarkastin olettaa, että metodin ensimmäinen parametri on "String kuka".

Terkuin,
Petri

**Comment by reettap** [comment]
Hei!
Olettaen että tarkoitetaan huolta siitä, että eri metodeissa parametrina saadun muuttujan nimi on eri, tässä ei ole ongelmaa.
