### ISSUE TITLE
Osa 06 / 06 Ohjelmasta kokonaisuuteen ja takaisin: epäselvyyksiä materiaalissa

### ISSUE THREAD

**Issue by AriMartti** [rage/ohjelmointi-19#58]
(https://ohjelmointi-19.mooc.fi/osa-6/6-ongelmasta-kokonaisuuteen-ja-takaisin-osiin)

jokaisessa koodiesimerkissä, missä pääohjelmasta luodaan käyttöliittymäolio, on ennen käyttöliittymäolion luontia turha rivi `Scanner lukija = new Scanner(System.in);`.

Tämä ei ole lainkaan olennaista luvun sisällön kannalta, kun jossain kohtaa on kumminkin tarkoitus kertoa että syötteitä voi lukea muutenkin kuin komentoriviltä rivisyötteenä.

**Comment by AriMartti** [comment]
Otsikon ulkopuolelta: Mihin liittyy seuraava lainaus samalta sivulta:

> 
> Tässä osassa kannattaa tutkiskella HashMapin valmiiksi tarjoamia metodeja... Vaihtoehtoisesti long-tyyppisen muuttujan saa muunnettua int-tyyppiseksi seuraavalla tavalla.
> 
> `long lukuLongina = 1L;`
> `int lukuInttina = (int) lukuLongina;`

**Comment by reettap** [comment]
Alempi korjattu, kiitos! :)
Scanner on tuossa paikallaan, sillä Kayttoliittyma-luokan konstruktori vaatii tässä esimerkissä Scannerin. Siksi Scanner on luotava pääohjelmassa ennen kayttöliittyma-olion kutsua.
