### ISSUE TITLE
Osa 7_04 Järjestäminen - osio 2

### ISSUE THREAD

**Issue by pjehkonen** [rage/ohjelmointi-19#59]
Pienimmän arvon indeksi kohdassa esimerkkikoodissa esiintyy "new" joka estää koodin kääntymisen.

**Nyt:**
// indeksit:   0  1  2  3  4
int[] luvut = {6, 5, 8, 7, 11};
System.out.println("Pienimmän indeksi: " + new Paaohjelma.pienimmanIndeksi(luvut));

**Pitäisi olla:**
// indeksit:   0  1  2  3  4
int[] luvut = {6, 5, 8, 7, 11};
System.out.println("Pienimmän indeksi: " + Paaohjelma.pienimmanIndeksi(luvut));

**Comment by reettap** [comment]
Kiitos, tämä on korjattu :)
