### ISSUE TITLE
Osa 6.1: pieni typo

### ISSUE THREAD

**Issue by jtompuri** [rage/ohjelmointi-19#60]
"Metodia ei ole kuitenkaan määritelty Henkilö-luokan sisälle sillä vaikka se käsittelee parametrinaan **saamaan** henkilöolioa, se on juuri kirjoitetun pääohjelman apumetodi, jonka avulla pääohjelma on saatu kirjoitettua selkeämmin."

=> "Metodia ei ole kuitenkaan määritelty Henkilö-luokan sisälle sillä vaikka se käsittelee parametrinaan **saamaansa** henkilöolioa, se on juuri kirjoitetun pääohjelman apumetodi, jonka avulla pääohjelma on saatu kirjoitettua selkeämmin."

**Comment by reettap** [comment]
Korjattu, kiitos!
