### ISSUE TITLE
6.3: Sulkeva sulkumerkki puuttuu esimerkkikoodista

### ISSUE THREAD

**Issue by jtompuri** [rage/ohjelmointi-19#61]
Kappeleen "Suurpiirteinen vertailu hajautusarvon avulla" esimerkkikoodista puuttuu yhdet sulkevat sulkumerkit riveiltä:

`System.out.println(lainaajat.get(new Kirja("Oliokirja", 2000, "..."));
System.out.println(lainaajat.get(new Kirja("Test Driven Development", 1999, "..."));`
=> 
`System.out.println(lainaajat.get(new Kirja("Oliokirja", 2000, "...")));
System.out.println(lainaajat.get(new Kirja("Test Driven Development", 1999, "...")));`

Esimerkkikoodi on kahteen kertaan kappaleessa, joten virhe on hyvä korjata molempiin esiintymiin.

**Comment by reettap** [comment]
Korjattu, kiitos!
