### ISSUE TITLE
Osa07_07 Arvosanatilastot

### ISSUE THREAD

**Issue by AriMartti** [rage/ohjelmointi-19#64]
Arvosanataulukossa on bugi, joka selviää tehtävää palautettaessa. Pistemäärällä 90 ei saa arvosanaa lainkaan, kun arvosanan 4 saa pistemäärää 90 pienemmillä pisteilla ja arvosanan 5 pistemäärää 91 suuremmilla pisteillä. HiddenTest kertoi minulle, että olin tulostanut yhden arvosanan 0 tähden liikaa ja huomasin ton debugatessani, mitä arvoja pisteet arvosanoiksi muuttava metodini palauttaa.

![image](https://user-images.githubusercontent.com/876555/53103294-003cc700-3536-11e9-84b8-2e130575bd81.png)

**Comment by reettap** [comment]
Kiitos, tämä on korjattu! :)
