### ISSUE TITLE
Osa06_10.Autorekisterikeskus: tehtäväantosivulla esitetyn konstruktin 'public Rekisterinumero(String rekNro, String maa)' parametrien järjestys on eri kuin tehtäväpohjassa tai esimerkkiohjelmassa

### ISSUE THREAD

**Issue by toniramo** [rage/ohjelmointi-19#66]
Sivulla https://ohjelmointi-19.mooc.fi/osa-6/3-olioiden-samankaltaisuus tehtävän **Autorekisterikeskus** (tai Osa06_10.Autorekisterikeskus) kuvauksessa Rekisterinumero-luokan konstruktin parametrit on määritelty eri järjestyksessä kuin mitä ohjelmointiympäristön tehtäväpohjassa tai sivun esimerkkiohjelmassa oletetaan. Sivua luettu 2019-02-22 11:50.

Sivulla Rekisterinumero-luokan konstrukti on esitetty näin (parametrina ensin rekisterinumero, sitten maatunnus):
```
// ...
    public Rekisterinumero(String rekNro, String maa) {
       this.rekNro = rekNro;
       this.maa = maa;
    }
// ...
```
Sen sijaan tehtäväpohjassa parametrit syötetään eri järjestyksessä (ensin maatunnus, sitten rekisterinumero):

```
// ...
    public Rekisterinumero(String maa, String rekNro) {
        this.rekNro = rekNro;
        this.maa = maa;
    }
// ...
```

Sama oletus on sivun esimerkkiohjelmassa (ensin maatunnus, sitten rekisterinumero):
```
// ...
public static void main(String[] args) {
    Rekisterinumero rek1 = new Rekisterinumero("FI", "ABC-123");
    Rekisterinumero rek2 = new Rekisterinumero("FI", "UXE-465");
    Rekisterinumero rek3 = new Rekisterinumero("D", "B WQ-431");
// ...
```

Kommentti:
Virhe on pieni, mutta voi aiheuttaa hämmennystä, kun tehtävämateriaalia käy läpi ensimmäisen kerran. Onneksi ohjelmointiympäristön tehtäväpohja vastaa esimerkkiohjelman oletettua toteutusta, joten tämä saattanee jäädä helposti huomaamattakin.

**Comment by reettap** [comment]
Korjattu, kiitos! :)
