### ISSUE TITLE
Osa 6 monivalintatehtävä "Olio hajautustaulun arvona" - esimerkissä metodin kutsu on väärä

### ISSUE THREAD

**Issue by tikauppi** [rage/ohjelmointi-19#67]
Luokan Henkilo metodi 
```
    public String getNimi() {
        return nimi;
    }
```
ja kutsu pääohjelmassa on 
   henkilotaulu.put(kasper.**getName**(), kasper);

**Comment by Redande** [comment]
Hei,

Kiitos kun ilmoitit tämän! Tehtävä on nyt korjattu.
