### ISSUE TITLE
Parempi ohjeistus tehtävien palauttamiseen

### ISSUE THREAD

**Issue by ljleppan** [rage/ohjelmointi-19#7]
Telegramissa raportoitu usean (5+) ihmisen missaneen ohje jossa kerrotaan kuinka NB:stä käsin palautetaan tehtäviä. Ovat palauttaneet käsin zipattuja tiedostoja TMC:n verkkokälin kautta.

Materiaaliin voisi tämän estämiseksi laittaa ekan tehtävän yhteyteen jonkin ison punaisen huomion jossa käsketään erikseen lukea TMC-Netbeansin asennusohjeen lopussa oleva palautusohje.

**Comment by nygrenh** [comment]
Thanks! Toteutin kummatkin sillä muutoksella, että laitoin palautusohjeet jokaisen ohjelmointitehtävän yhteyteen.
