### ISSUE TITLE
07_09 LintubongarinTietokanta

### ISSUE THREAD

**Issue by vepa69** [rage/ohjelmointi-19#71]
Onko tarkoitus että komneto "Tilasto" tulostaa todella kannan sisällön havintojen mukaan järjestyksessä isoimmasta pienimpään? Ianakin omalta osaltani tehtävä meni läpi ilman tätä järjestelyäkin. (Kun asia jäi itseni vaivaamaan olen nyt muutanut oiman koodin niin että se myös tekee järjestelyn jota voisi olettaa tehtävän mallitulostuksen perusteella vaadittavan).

**Comment by reettap** [comment]
Kiitos kysymyksestä! 
Tässä tehtävässä ei ole erikseen pyydetty mitään tiettyä järjestystä, joten mikä tahansa järjestys kelpaa :)
