### ISSUE TITLE
Osa 8 - Luokan periminen. Polymorfismimonivalinnan esimerkkikoodissa kirjoitusvirhe.

### ISSUE THREAD

**Issue by stripeswamp** [rage/ohjelmointi-19#74]
Osassa 8 - Luokan periminen -osuuden polymorfismimonivalinnan esimerkkikoodissa on virhe.

"...
public static void main(String[] args) {
    Opiskelija opiskelija = new Opiskelija(Kenny, 23, 140);
..."

Eli mikään valinnoisa ei ole oikea, koska tuo esimerkkikoodi ei toimi tai tuottaisi siis virheen.
Ilmeisesti materiaaliin tulisi korjata Kenny -> "Kenny", koska Opiskelija vastaanottaa String, int, int.

**Comment by SiniCC** [comment]
Tämänkin jälkeen vastaus vaihtoehdot ovat väärät, sillä iän jälkeen pitäisi palautua myös sana "vuotta", oikea vastaus olisi: Kenny (23 vuotta) 140 op, Kenny (23 vuotta) 140 op, Kenny (23 vuotta) 140 op

---------------------------------------
public String toString() {
       return nimi + " (" + ika + " vuotta) ";
    }

**Comment by Redande** [comment]
Hei,

Kiitos kun ilmoitit tämän! Tehtävä on nyt korjattu.
