### ISSUE TITLE
9_15 testit päästävät virheellisen koodin läpi

### ISSUE THREAD

**Issue by reettaV** [rage/ohjelmointi-19#76]
Tehtävän testeistä kellonaikaHyvaksyyOikeat() testaa puutteellisesti tuntien lukemia. Testisyöte on 
"20:00:00", "11:24:00", "04:59:31", "14:41:16", "23:32:23", "20:00:59", mutta syöte ei testaa lainkaan kellonaikoja, joissa tunnin jälkimmäinen numero on enemmän kuin 4. Tämän seurauksena läpi pääsee sellainen koodi, joka rajaa kyseisen luvun olemaan korkeintaan 4, ja jonka mielestä esimerkiksi kellonaika 05:00:00 on väärin. 

Huomasin tämän, kun Telegramin puolella tuli vastaan kurssikaverin koodi, jonka testit eivät menneet läpi. Luulin herjan johtuvan virheestä tuntien käsittelyssä, ja yllätyin kun tehtävä meni hetken päästä läpi yksillä lisäsuluilla. 

Tämä koodi meni siis testeiltä läpi: 

```
public boolean kellonaika(String merkkijono) {

        String[] osaset = merkkijono.split("(?!^)");
        
        return (((osaset[0].matches("[0-2]") && osaset[1].matches("[0-3]")) || (osaset[0].matches("[0-1]") && osaset[1].matches("[0-4]")))
                && osaset[3].matches("[0-5]") // 
                && osaset[4].matches("[0-9]")
                && osaset[6].matches("[0-5]")
                && osaset[7].matches("[0-9]"));
}
```

**Comment by reettap** [comment]
Kiitos, nyt on lisätty testejä :)
