### ISSUE TITLE
Osa 7_05 jarjestaMerkkijonot: pieni typo

### ISSUE THREAD

**Issue by jtompuri** [rage/ohjelmointi-19#77]
Tehtävänannossa on:
`public static void jarjestaMerkkijonot(ArrayList<String> luvut)`

Koska kyseessä on merkkijono, niin pitäisi varmaan lukea:
`public static void jarjestaMerkkijonot(ArrayList<String> merkkijonot)`

Mallivastauksessa on "merkkijonot".

**Comment by reettap** [comment]
Korjattu, kiitos!
