### ISSUE TITLE
Osa 7: Testisyötteen antaminen Scannerille: pieni typo esimerkin koodissa

### ISSUE THREAD

**Issue by jtompuri** [rage/ohjelmointi-19#78]
Osa 7: Ohjelmien automaattinen testaaminen / Testisyötteen antaminen Scannerille -esimerkissä while-silmukassa on:
`luettu.add(rivi);`

...kun pitäisi olla:
`luetut.add(rivi);`

Lisäksi if-lauseessa on:
`if (luetut.sisaltaa("kuusi")) {`

...kun pitäisi olla:
`if (luetut.contains("kuusi")) {`

**Comment by reettap** [comment]
Kiitos, korjattu! :)
