### ISSUE TITLE
Osa 4 tehtävä 10 puolipistevirhe esimerkissä

### ISSUE THREAD

**Issue by sepes** [rage/ohjelmointi-19#89]
https://ohjelmointi-19.mooc.fi/osa-4/1-tiedon-lukeminen-ja-tiedostot

Vanhin tiedostossa tehtävän esimerkissä on puolipistevirhe rivillä 19

// luodaan lukija tiedoston lukemista varten
try (Scanner tiedostonLukija = new Scanner(new File("henkilot.csv"))) {

    // luetaan kaikki tiedoston rivit
    while (tiedostonLukija.hasNextLine()) {
        String rivi = tiedostonLukija.nextLine();

        // mikäli rivi on tyhjä, ei käsitellä sitä
        if (rivi.trim().length() == 0) {
            continue;
        }

        // muulloin tulostetaan tiedot
        String[] osat = rivi.split(",");

        String nimi = osat[0];
        int vuosi = Integer.valueOf(osat[1]);

        System.out.println(nimi + " on syntynyt vuonna " + vuosi)

    }
} catch (Exception e) {
    System.out.println("Virhe: " + e.getMessage());
}

**Comment by reettap** [comment]
Korjattu, kiitos! :)
