### ISSUE TITLE
Osa 1 Tehtävä 6, Odotettiim ett' System.out.println komentoja on 1. Nyt niitä oli 0.

### ISSUE THREAD

**Issue by Niko9911** [rage/ohjelmointi-19#90]
prinf käyttö tulisi olla tässä tehtävässä yhtä sallittu. Myöskin sen käyttö on huomattavasti viisaampaa, kuin yhdistellä stringejä plussilla

**Comment by reettap** [comment]
Hei!
Tehtävän tarkoituksena on opettaa muuttujien käyttöä, joten merkkijonojen summailu on tässä tarkoituksenmukaista. Myöhemmissä testeissä tulostukseen saa käyttää haluamaansa keinoa.
