### ISSUE TITLE
Tehtävä 12_01 Sovellukseni.

### ISSUE THREAD

**Issue by Propagationdelay** [rage/ohjelmointi-19#91]
Mä onnistuin jotenkin sössimään tehtävän 12_01 Sovellukseni. Olen poistanut sen useasti ja ladannut uudestaan. Mutta aina tulee viallinen versio, eli versio jossa jotain on pielessä, koska punainen täplä. Miten saisin koneelleni ehjän version ko. tehtävästä

**Comment by reettap** [comment]
Hei! Kurssin tukikanavat löytää täältä: https://ohjelmointi-19.mooc.fi/tukivaylat
