### ISSUE TITLE
Osa11_04_Rajatut_taulukossa  for loopin ehto jättää "mihin" indeksin arvon pois summasta

### ISSUE THREAD

**Issue by Militantti-talitintti** [rage/ohjelmointi-19#92]
Eikö tarkoitus ole sisällyttää summaan myös "mihin" indeksissä oleva arvo? Tällöin ehdon pitäisi olla i <= mihin ja aiemmin "mihin" -muuttujan tarkistuksessa sen arvo saisi olla enintään taulukko.length -1.

**Comment by reettap** [comment]
Kiitos, korjattu! :)
