### ISSUE TITLE
Osa 11: lista-tehtävän esimerkin poista()-metodissa ajatusvirhe

### ISSUE THREAD

**Issue by FinThunderstorm** [rage/ohjelmointi-19#96]
![image](https://user-images.githubusercontent.com/6292793/55689186-41742380-598a-11e9-87a5-11df9471983a.png)
Tainnut tapahtua ajatuskatkos; varmaan tarkoitus olla public boolean poista(T arvo) tai palautukset unohtunut koodiin.

**Comment by reettap** [comment]
Korjattu, kiitos! :)
