### ISSUE TITLE
Osa 11: Hajautustauluun lisääminen, osa 2

### ISSUE THREAD

**Issue by areee** [rage/ohjelmointi-19#99]
![Näyttökuva 2019-4-8 kello 19 24 54](https://user-images.githubusercontent.com/10089872/55741125-332f1180-5a35-11e9-8c76-b9f15b0f5567.png)

_Kasvata_-metodin _for_-toistolauseessa kutsutaan _kopioi_-metodia _uusi_- ja _indeksista_-parametreilla. Tuo _indeksista_ kuuluisi kaiketi olla for-lauseen _i_-muuttuja.

**Comment by reettap** [comment]
Korjattu, kiitos! :)
